### ISSUE TITLE
Efficiency of server space usage

### ISSUE THREAD

**Issue by jebyrnes** [zooniverse/ff-import#25]
So, after working with this script for two years, and now seriously scaling up some of the Floating Forests inputs, I'm noticing something that is becoming problematic - and might be so for the eventual web-based implementation. Namely, the large space usage of this script. Unarchiving all of the scenes at once means that this script has a hard time scaling. For example, I work on a HPCC, and am alloted 2TB of storage. If I want to download all of the scenes for an area (just UTM zone 12 for Baja, for example), I have to limit myself to working with ~500 scenes at a time in order to avoid running out of disk space. I don't know if this would become problematic on an AWS instance or somesuch (or become prohibitively expensive). Would it be possible to work the extraction into the script, so a scene is extracted just in time before processing, then the unarchived directory is removed after processing of that scene is done?

**Comment by adammcmaster** [comment]
Unfortunately I don't think we will be able to allocate developer time for this, since as I understand it this will be replaced at some point with a new pipeline. On AWS I would suggest using EFS when running this, since with that you don't need to allocate storage in advance and it's pretty cheap if you only store things in there temporarily.
